#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class CantidadRevistasXDeporteResultSet0
	{
		private string _deporte;
		public virtual string Deporte
		{
			get
			{
				return this._deporte;
			}
			set
			{
				this._deporte = value;
			}
		}
		
		private int? _total;
		public virtual int? Total
		{
			get
			{
				return this._total;
			}
			set
			{
				this._total = value;
			}
		}
		
	}
}
#pragma warning restore 1591
