#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class ListadoColeccionResultSet0
	{
		private int _idDetalleColeccion;
		public virtual int idDetalleColeccion
		{
			get
			{
				return this._idDetalleColeccion;
			}
			set
			{
				this._idDetalleColeccion = value;
			}
		}
		
		private int _idColeccion;
		public virtual int idColeccion
		{
			get
			{
				return this._idColeccion;
			}
			set
			{
				this._idColeccion = value;
			}
		}
		
		private string _nombreColeccion;
		public virtual string NombreColeccion
		{
			get
			{
				return this._nombreColeccion;
			}
			set
			{
				this._nombreColeccion = value;
			}
		}
		
		private string _estado;
		public virtual string Estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private string _nombreCapitulo;
		public virtual string NombreCapitulo
		{
			get
			{
				return this._nombreCapitulo;
			}
			set
			{
				this._nombreCapitulo = value;
			}
		}
		
		private int? _capitulo;
		public virtual int? Capitulo
		{
			get
			{
				return this._capitulo;
			}
			set
			{
				this._capitulo = value;
			}
		}
		
	}
}
#pragma warning restore 1591
