#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class ModeloDominio : OpenAccessContext, IModeloDominioUnitOfWork
	{
		private static string connectionStringName = @"ElGrafico_DesaConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("ModeloDominio.rlinq");
		
		public ModeloDominio()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public ModeloDominio(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public ModeloDominio(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public ModeloDominio(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public ModeloDominio(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Revista> Revistas 
		{
			get
			{
				return this.GetAll<Revista>();
			}
		}
		
		public IQueryable<Deporte> Deportes 
		{
			get
			{
				return this.GetAll<Deporte>();
			}
		}
		
		public IQueryable<Tapa> Tapas 
		{
			get
			{
				return this.GetAll<Tapa>();
			}
		}
		
		public IQueryable<Estado> Estados 
		{
			get
			{
				return this.GetAll<Estado>();
			}
		}
		
		public IQueryable<DetalleColeccion> DetalleColeccions 
		{
			get
			{
				return this.GetAll<DetalleColeccion>();
			}
		}
		
		public IQueryable<Coleccion> Coleccions 
		{
			get
			{
				return this.GetAll<Coleccion>();
			}
		}
		
		public IEnumerable<ListadoDeRevistasResultSet0> SP_ListadoDeRevistas()
		{
			int returnValue;
			return SP_ListadoDeRevistas(out returnValue);
		}
		
		public IEnumerable<ListadoDeRevistasResultSet0> SP_ListadoDeRevistas(out int returnValue)
		{
			OAParameter parameterReturnValue = new OAParameter();
		    parameterReturnValue.Direction = ParameterDirection.ReturnValue;
		    parameterReturnValue.ParameterName = "parameterReturnValue";
		
			IEnumerable<ListadoDeRevistasResultSet0> queryResult = this.ExecuteQuery<ListadoDeRevistasResultSet0>("[dbo].[ListadoDeRevistas]", CommandType.StoredProcedure, parameterReturnValue);
		
			returnValue = parameterReturnValue.Value == DBNull.Value 
				? -1
				: (int)parameterReturnValue.Value;
		
			return queryResult;
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of ModeloDominio.
		/// </summary>
		/// <param name="config">The BackendConfiguration of ModeloDominio.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IModeloDominioUnitOfWork : IUnitOfWork
	{
		IQueryable<Revista> Revistas
		{
			get;
		}
		IQueryable<Deporte> Deportes
		{
			get;
		}
		IQueryable<Tapa> Tapas
		{
			get;
		}
		IQueryable<Estado> Estados
		{
			get;
		}
		IQueryable<DetalleColeccion> DetalleColeccions
		{
			get;
		}
		IQueryable<Coleccion> Coleccions
		{
			get;
		}
		IEnumerable<ListadoDeRevistasResultSet0> SP_ListadoDeRevistas();
		IEnumerable<ListadoDeRevistasResultSet0> SP_ListadoDeRevistas(out int returnValue);
	}
}
#pragma warning restore 1591
